class LogLevel:
    DEBUG: int
    INFO:  int
    WARN:  int
    ERROR: int
    FATAL: int

class Logger:
    def __init__(
        self,
        path:  str,
        level: int = LogLevel.INFO
    ) -> None: ...
    def log(
        self,
        level:   int,
        message: str,
        forced:  bool = False
    ) -> None: ...
    def debug(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def warn(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    def fatal(self, message: str) -> None: ...
    def close(self) -> None: ...